///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxDatabase
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxDatabaseRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("433e9601-1d78-4cca-8b70-baf669adfae5")]
    public partial class RxDatabaseRepository : RepoGenBaseFolder
    {
        static RxDatabaseRepository instance = new RxDatabaseRepository();
        RxDatabaseRepositoryFolders.DemoApplicationAppFolder _demoapplication;
        RxDatabaseRepositoryFolders.DepartmentListAppFolder _departmentlist;

        /// <summary>
        /// Gets the singleton class instance representing the RxDatabaseRepository element repository.
        /// </summary>
        [RepositoryFolder("433e9601-1d78-4cca-8b70-baf669adfae5")]
        public static RxDatabaseRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxDatabaseRepository() 
            : base("RxDatabaseRepository", "/", null, 0, false, "433e9601-1d78-4cca-8b70-baf669adfae5", ".\\RepositoryImages\\RxDatabaseRepository433e9601.rximgres")
        {
            _demoapplication = new RxDatabaseRepositoryFolders.DemoApplicationAppFolder(this);
            _departmentlist = new RxDatabaseRepositoryFolders.DepartmentListAppFolder(this);
        }

#region Variables

        string _Gender = "rdbMale";

        /// <summary>
        /// Gets or sets the value of variable Gender.
        /// </summary>
        [TestVariable("14db4c9b-793e-4f23-a599-450366ae0e82")]
        public string Gender
        {
            get { return _Gender; }
            set { _Gender = value; }
        }

        string _Department = "Project Management";

        /// <summary>
        /// Gets or sets the value of variable Department.
        /// </summary>
        [TestVariable("4df2c91b-1ba3-457a-8208-563447a0d3bc")]
        public string Department
        {
            get { return _Department; }
            set { _Department = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("433e9601-1d78-4cca-8b70-baf669adfae5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The DemoApplication folder.
        /// </summary>
        [RepositoryFolder("d074c66c-e8e3-4f93-a541-de29a8eb9569")]
        public virtual RxDatabaseRepositoryFolders.DemoApplicationAppFolder DemoApplication
        {
            get { return _demoapplication; }
        }

        /// <summary>
        /// The DepartmentList folder.
        /// </summary>
        [RepositoryFolder("ea3ee1bb-76a8-48fa-93a0-0a935a5739df")]
        public virtual RxDatabaseRepositoryFolders.DepartmentListAppFolder DepartmentList
        {
            get { return _departmentlist; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class RxDatabaseRepositoryFolders
    {
        /// <summary>
        /// The DemoApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("d074c66c-e8e3-4f93-a541-de29a8eb9569")]
        public partial class DemoApplicationAppFolder : RepoGenBaseFolder
        {
            RxDatabaseRepositoryFolders.DatabaseTabFolder _databasetab;
            RxDatabaseRepositoryFolders.RxTabUIElementsFolder _rxtabuielements;
            RxDatabaseRepositoryFolders.RxTabUploadFolder _rxtabupload;
            RepoItemInfo _databaseInfo;
            RepoItemInfo _btnexitInfo;
            RepoItemInfo _uielementtestareaInfo;
            RepoItemInfo _uploadtestingInfo;

            /// <summary>
            /// Creates a new DemoApplication  folder.
            /// </summary>
            public DemoApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DemoApplication", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "d074c66c-e8e3-4f93-a541-de29a8eb9569", "")
            {
                _databasetab = new RxDatabaseRepositoryFolders.DatabaseTabFolder(this);
                _rxtabuielements = new RxDatabaseRepositoryFolders.RxTabUIElementsFolder(this);
                _rxtabupload = new RxDatabaseRepositoryFolders.RxTabUploadFolder(this);
                _databaseInfo = new RepoItemInfo(this, "Database", "?/?/tabpage[@accessiblename='Test database']", 30000, null, "44a1f073-f9bd-4c27-8a7b-2d78baeb8274");
                _btnexitInfo = new RepoItemInfo(this, "BtnExit", "button[@controlname='RxButtonExit']", 30000, null, "2598a21b-f421-414d-9b6d-0cdcb44cbd8c");
                _uielementtestareaInfo = new RepoItemInfo(this, "UIElementTestArea", "?/?/tabpage[@accessiblename='UI-element test area']", 30000, null, "f05255d4-bf18-4ffc-8ce9-4b9d80ea284f");
                _uploadtestingInfo = new RepoItemInfo(this, "UploadTesting", "?/?/tabpage[@accessiblename='Upload testing']", 30000, null, "a4c20539-3fcd-4e4c-9a9f-9f0f4f01e2b2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d074c66c-e8e3-4f93-a541-de29a8eb9569")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d074c66c-e8e3-4f93-a541-de29a8eb9569")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Database item.
            /// </summary>
            [RepositoryItem("44a1f073-f9bd-4c27-8a7b-2d78baeb8274")]
            public virtual Ranorex.TabPage Database
            {
                get
                {
                    return _databaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Database item info.
            /// </summary>
            [RepositoryItemInfo("44a1f073-f9bd-4c27-8a7b-2d78baeb8274")]
            public virtual RepoItemInfo DatabaseInfo
            {
                get
                {
                    return _databaseInfo;
                }
            }

            /// <summary>
            /// The BtnExit item.
            /// </summary>
            [RepositoryItem("2598a21b-f421-414d-9b6d-0cdcb44cbd8c")]
            public virtual Ranorex.Button BtnExit
            {
                get
                {
                    return _btnexitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnExit item info.
            /// </summary>
            [RepositoryItemInfo("2598a21b-f421-414d-9b6d-0cdcb44cbd8c")]
            public virtual RepoItemInfo BtnExitInfo
            {
                get
                {
                    return _btnexitInfo;
                }
            }

            /// <summary>
            /// The UIElementTestArea item.
            /// </summary>
            [RepositoryItem("f05255d4-bf18-4ffc-8ce9-4b9d80ea284f")]
            public virtual Ranorex.TabPage UIElementTestArea
            {
                get
                {
                    return _uielementtestareaInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The UIElementTestArea item info.
            /// </summary>
            [RepositoryItemInfo("f05255d4-bf18-4ffc-8ce9-4b9d80ea284f")]
            public virtual RepoItemInfo UIElementTestAreaInfo
            {
                get
                {
                    return _uielementtestareaInfo;
                }
            }

            /// <summary>
            /// The UploadTesting item.
            /// </summary>
            [RepositoryItem("a4c20539-3fcd-4e4c-9a9f-9f0f4f01e2b2")]
            public virtual Ranorex.TabPage UploadTesting
            {
                get
                {
                    return _uploadtestingInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The UploadTesting item info.
            /// </summary>
            [RepositoryItemInfo("a4c20539-3fcd-4e4c-9a9f-9f0f4f01e2b2")]
            public virtual RepoItemInfo UploadTestingInfo
            {
                get
                {
                    return _uploadtestingInfo;
                }
            }

            /// <summary>
            /// The DatabaseTab folder.
            /// </summary>
            [RepositoryFolder("d1b35100-06b2-4568-84e6-678337240c68")]
            public virtual RxDatabaseRepositoryFolders.DatabaseTabFolder DatabaseTab
            {
                get { return _databasetab; }
            }

            /// <summary>
            /// The RxTabUIElements folder.
            /// </summary>
            [RepositoryFolder("cafc4c2f-94a6-412b-a577-e89f9226754b")]
            public virtual RxDatabaseRepositoryFolders.RxTabUIElementsFolder RxTabUIElements
            {
                get { return _rxtabuielements; }
            }

            /// <summary>
            /// The RxTabUpload folder.
            /// </summary>
            [RepositoryFolder("253bf77e-c9ef-41cc-9335-7729aa02a1a4")]
            public virtual RxDatabaseRepositoryFolders.RxTabUploadFolder RxTabUpload
            {
                get { return _rxtabupload; }
            }
        }

        /// <summary>
        /// The DatabaseTabFolder folder.
        /// </summary>
        [RepositoryFolder("d1b35100-06b2-4568-84e6-678337240c68")]
        public partial class DatabaseTabFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _ageInfo;
            RepoItemInfo _selectmaleInfo;
            RepoItemInfo _btndepartmentlistInfo;
            RepoItemInfo _btnaddentryInfo;
            RepoItemInfo _counterentriesInfo;

            /// <summary>
            /// Creates a new DatabaseTab  folder.
            /// </summary>
            public DatabaseTabFolder(RepoGenBaseFolder parentFolder) :
                    base("DatabaseTab", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "d1b35100-06b2-4568-84e6-678337240c68", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First name']", 30000, null, "81f54b8e-b469-4ddf-8645-58956dc3b68e");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last name']", 30000, null, "c3b3978e-28c5-4d20-bf22-9a3b5d142105");
                _ageInfo = new RepoItemInfo(this, "Age", "?/?/text[@controlname='upDownEdit']", 30000, null, "25d04ce8-a039-4f0d-b3fc-9b4c5d26dbbf");
                _selectmaleInfo = new RepoItemInfo(this, "SelectMale", "?/?/radiobutton[@controlname=$Gender]", 30000, null, "d0f03f67-3675-44cd-8006-ffd22a31d11f");
                _btndepartmentlistInfo = new RepoItemInfo(this, "BtnDepartmentList", "?/?/button[@accessiblename='Open']", 30000, null, "01449310-d7ae-47b7-a46b-526a69c3ffb6");
                _btnaddentryInfo = new RepoItemInfo(this, "BtnAddEntry", "button[@controlname='btnAddPerson']", 30000, null, "a4abb092-12b3-4466-8d6d-7e61b59a63f7");
                _counterentriesInfo = new RepoItemInfo(this, "CounterEntries", "text[@controlname='lblNumberOfPersonsNumber']", 30000, null, "0943dd17-acbb-4738-bf91-f7e22de8636c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d1b35100-06b2-4568-84e6-678337240c68")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d1b35100-06b2-4568-84e6-678337240c68")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("81f54b8e-b469-4ddf-8645-58956dc3b68e")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("81f54b8e-b469-4ddf-8645-58956dc3b68e")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("c3b3978e-28c5-4d20-bf22-9a3b5d142105")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("c3b3978e-28c5-4d20-bf22-9a3b5d142105")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Age item.
            /// </summary>
            [RepositoryItem("25d04ce8-a039-4f0d-b3fc-9b4c5d26dbbf")]
            public virtual Ranorex.Text Age
            {
                get
                {
                    return _ageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Age item info.
            /// </summary>
            [RepositoryItemInfo("25d04ce8-a039-4f0d-b3fc-9b4c5d26dbbf")]
            public virtual RepoItemInfo AgeInfo
            {
                get
                {
                    return _ageInfo;
                }
            }

            /// <summary>
            /// The SelectMale item.
            /// </summary>
            [RepositoryItem("d0f03f67-3675-44cd-8006-ffd22a31d11f")]
            public virtual Ranorex.RadioButton SelectMale
            {
                get
                {
                    return _selectmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The SelectMale item info.
            /// </summary>
            [RepositoryItemInfo("d0f03f67-3675-44cd-8006-ffd22a31d11f")]
            public virtual RepoItemInfo SelectMaleInfo
            {
                get
                {
                    return _selectmaleInfo;
                }
            }

            /// <summary>
            /// The BtnDepartmentList item.
            /// </summary>
            [RepositoryItem("01449310-d7ae-47b7-a46b-526a69c3ffb6")]
            public virtual Ranorex.Button BtnDepartmentList
            {
                get
                {
                    return _btndepartmentlistInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnDepartmentList item info.
            /// </summary>
            [RepositoryItemInfo("01449310-d7ae-47b7-a46b-526a69c3ffb6")]
            public virtual RepoItemInfo BtnDepartmentListInfo
            {
                get
                {
                    return _btndepartmentlistInfo;
                }
            }

            /// <summary>
            /// The BtnAddEntry item.
            /// </summary>
            [RepositoryItem("a4abb092-12b3-4466-8d6d-7e61b59a63f7")]
            public virtual Ranorex.Button BtnAddEntry
            {
                get
                {
                    return _btnaddentryInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddEntry item info.
            /// </summary>
            [RepositoryItemInfo("a4abb092-12b3-4466-8d6d-7e61b59a63f7")]
            public virtual RepoItemInfo BtnAddEntryInfo
            {
                get
                {
                    return _btnaddentryInfo;
                }
            }

            /// <summary>
            /// The CounterEntries item.
            /// </summary>
            [RepositoryItem("0943dd17-acbb-4738-bf91-f7e22de8636c")]
            public virtual Ranorex.Text CounterEntries
            {
                get
                {
                    return _counterentriesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CounterEntries item info.
            /// </summary>
            [RepositoryItemInfo("0943dd17-acbb-4738-bf91-f7e22de8636c")]
            public virtual RepoItemInfo CounterEntriesInfo
            {
                get
                {
                    return _counterentriesInfo;
                }
            }
        }

        /// <summary>
        /// The RxTabUIElementsFolder folder.
        /// </summary>
        [RepositoryFolder("cafc4c2f-94a6-412b-a577-e89f9226754b")]
        public partial class RxTabUIElementsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _treeviewInfo;
            RepoItemInfo _pnlcolourpanelInfo;
            RepoItemInfo _rdbredlightInfo;
            RepoItemInfo _ranorizeyourselfin20minutesInfo;

            /// <summary>
            /// Creates a new RxTabUIElements  folder.
            /// </summary>
            public RxTabUIElementsFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabUIElements", "?/?/tabpage[@controlname='RxTabUIElements']", parentFolder, 30000, null, false, "cafc4c2f-94a6-412b-a577-e89f9226754b", "")
            {
                _treeviewInfo = new RepoItemInfo(this, "TreeView", "?/?/tree[@accessiblename='Tree view']", 30000, null, "08395e38-f052-40e2-8334-7775cf639859");
                _pnlcolourpanelInfo = new RepoItemInfo(this, "PnlColourPanel", "container[@controlname='grpBox']/?/?/container[@controlname='pnlColourPanel']", 30000, null, "64ba0d24-eb03-463c-9e36-81eaa965a418");
                _rdbredlightInfo = new RepoItemInfo(this, "RdbRedLight", "container[@controlname='grpBox']/?/?/radiobutton[@controlname='rdbRedLight']", 30000, null, "ce13e94f-774f-481e-a048-a31c1dc2856d");
                _ranorizeyourselfin20minutesInfo = new RepoItemInfo(this, "RanorizeYourselfIn20Minutes", "tree[@controlname='treTestTreeView']//treeitem[@accessiblename~'^Ranorize\\ yourself\\ in\\ 20\\ m']", 30000, null, "7488448d-1018-4db0-a4e0-fbce758fe44f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cafc4c2f-94a6-412b-a577-e89f9226754b")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cafc4c2f-94a6-412b-a577-e89f9226754b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TreeView item.
            /// </summary>
            [RepositoryItem("08395e38-f052-40e2-8334-7775cf639859")]
            public virtual Ranorex.Tree TreeView
            {
                get
                {
                    return _treeviewInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The TreeView item info.
            /// </summary>
            [RepositoryItemInfo("08395e38-f052-40e2-8334-7775cf639859")]
            public virtual RepoItemInfo TreeViewInfo
            {
                get
                {
                    return _treeviewInfo;
                }
            }

            /// <summary>
            /// The PnlColourPanel item.
            /// </summary>
            [RepositoryItem("64ba0d24-eb03-463c-9e36-81eaa965a418")]
            public virtual Ranorex.Container PnlColourPanel
            {
                get
                {
                    return _pnlcolourpanelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PnlColourPanel item info.
            /// </summary>
            [RepositoryItemInfo("64ba0d24-eb03-463c-9e36-81eaa965a418")]
            public virtual RepoItemInfo PnlColourPanelInfo
            {
                get
                {
                    return _pnlcolourpanelInfo;
                }
            }

            /// <summary>
            /// The RdbRedLight item.
            /// </summary>
            [RepositoryItem("ce13e94f-774f-481e-a048-a31c1dc2856d")]
            public virtual Ranorex.RadioButton RdbRedLight
            {
                get
                {
                    return _rdbredlightInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbRedLight item info.
            /// </summary>
            [RepositoryItemInfo("ce13e94f-774f-481e-a048-a31c1dc2856d")]
            public virtual RepoItemInfo RdbRedLightInfo
            {
                get
                {
                    return _rdbredlightInfo;
                }
            }

            /// <summary>
            /// The RanorizeYourselfIn20Minutes item.
            /// </summary>
            [RepositoryItem("7488448d-1018-4db0-a4e0-fbce758fe44f")]
            public virtual Ranorex.TreeItem RanorizeYourselfIn20Minutes
            {
                get
                {
                    return _ranorizeyourselfin20minutesInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The RanorizeYourselfIn20Minutes item info.
            /// </summary>
            [RepositoryItemInfo("7488448d-1018-4db0-a4e0-fbce758fe44f")]
            public virtual RepoItemInfo RanorizeYourselfIn20MinutesInfo
            {
                get
                {
                    return _ranorizeyourselfin20minutesInfo;
                }
            }
        }

        /// <summary>
        /// The RxTabUploadFolder folder.
        /// </summary>
        [RepositoryFolder("253bf77e-c9ef-41cc-9335-7729aa02a1a4")]
        public partial class RxTabUploadFolder : RepoGenBaseFolder
        {
            RepoItemInfo _resetuploadInfo;
            RepoItemInfo _rbslowInfo;
            RepoItemInfo _btnstartuploadInfo;
            RepoItemInfo _uploadprogressbarInfo;

            /// <summary>
            /// Creates a new RxTabUpload  folder.
            /// </summary>
            public RxTabUploadFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabUpload", "?/?/tabpage[@controlname='RxTabUpload']", parentFolder, 30000, null, false, "253bf77e-c9ef-41cc-9335-7729aa02a1a4", "")
            {
                _resetuploadInfo = new RepoItemInfo(this, "ResetUpload", "?/?/element[@accessiblename='Reset upload']", 30000, null, "26106fcd-0578-4297-a82f-403bf9bd39a5");
                _rbslowInfo = new RepoItemInfo(this, "RBSlow", "?/?/radiobutton[@controlname='rBSlow']", 30000, null, "473217c2-465f-465b-a944-2720919be3ed");
                _btnstartuploadInfo = new RepoItemInfo(this, "BtnStartUpload", "button[@controlname='btnStartUpload']", 30000, null, "519b92c0-9512-432f-ad43-456124996e90");
                _uploadprogressbarInfo = new RepoItemInfo(this, "UploadProgressbar", "progressbar[@controlname='uploadProgressbar']", 30000, null, "086b4d0d-01e4-4189-b0e7-0b6d64f15d68");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("253bf77e-c9ef-41cc-9335-7729aa02a1a4")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("253bf77e-c9ef-41cc-9335-7729aa02a1a4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ResetUpload item.
            /// </summary>
            [RepositoryItem("26106fcd-0578-4297-a82f-403bf9bd39a5")]
            public virtual Ranorex.Unknown ResetUpload
            {
                get
                {
                    return _resetuploadInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ResetUpload item info.
            /// </summary>
            [RepositoryItemInfo("26106fcd-0578-4297-a82f-403bf9bd39a5")]
            public virtual RepoItemInfo ResetUploadInfo
            {
                get
                {
                    return _resetuploadInfo;
                }
            }

            /// <summary>
            /// The RBSlow item.
            /// </summary>
            [RepositoryItem("473217c2-465f-465b-a944-2720919be3ed")]
            public virtual Ranorex.RadioButton RBSlow
            {
                get
                {
                    return _rbslowInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RBSlow item info.
            /// </summary>
            [RepositoryItemInfo("473217c2-465f-465b-a944-2720919be3ed")]
            public virtual RepoItemInfo RBSlowInfo
            {
                get
                {
                    return _rbslowInfo;
                }
            }

            /// <summary>
            /// The BtnStartUpload item.
            /// </summary>
            [RepositoryItem("519b92c0-9512-432f-ad43-456124996e90")]
            public virtual Ranorex.Button BtnStartUpload
            {
                get
                {
                    return _btnstartuploadInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnStartUpload item info.
            /// </summary>
            [RepositoryItemInfo("519b92c0-9512-432f-ad43-456124996e90")]
            public virtual RepoItemInfo BtnStartUploadInfo
            {
                get
                {
                    return _btnstartuploadInfo;
                }
            }

            /// <summary>
            /// The UploadProgressbar item.
            /// </summary>
            [RepositoryItem("086b4d0d-01e4-4189-b0e7-0b6d64f15d68")]
            public virtual Ranorex.ProgressBar UploadProgressbar
            {
                get
                {
                    return _uploadprogressbarInfo.CreateAdapter<Ranorex.ProgressBar>(true);
                }
            }

            /// <summary>
            /// The UploadProgressbar item info.
            /// </summary>
            [RepositoryItemInfo("086b4d0d-01e4-4189-b0e7-0b6d64f15d68")]
            public virtual RepoItemInfo UploadProgressbarInfo
            {
                get
                {
                    return _uploadprogressbarInfo;
                }
            }
        }

        /// <summary>
        /// The DepartmentListAppFolder folder.
        /// </summary>
        [RepositoryFolder("ea3ee1bb-76a8-48fa-93a0-0a935a5739df")]
        public partial class DepartmentListAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _projectmanagementInfo;

            /// <summary>
            /// Creates a new DepartmentList  folder.
            /// </summary>
            public DepartmentListAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DepartmentList", "/list[@controlid='1000']", parentFolder, 30000, null, true, "ea3ee1bb-76a8-48fa-93a0-0a935a5739df", "")
            {
                _projectmanagementInfo = new RepoItemInfo(this, "ProjectManagement", "listitem[@text=$Department]", 30000, null, "2ccf86e7-cb7b-4275-80fe-89e49408bdb0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ea3ee1bb-76a8-48fa-93a0-0a935a5739df")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ea3ee1bb-76a8-48fa-93a0-0a935a5739df")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProjectManagement item.
            /// </summary>
            [RepositoryItem("2ccf86e7-cb7b-4275-80fe-89e49408bdb0")]
            public virtual Ranorex.ListItem ProjectManagement
            {
                get
                {
                    return _projectmanagementInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ProjectManagement item info.
            /// </summary>
            [RepositoryItemInfo("2ccf86e7-cb7b-4275-80fe-89e49408bdb0")]
            public virtual RepoItemInfo ProjectManagementInfo
            {
                get
                {
                    return _projectmanagementInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}