///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxDatabase
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxDatabaseRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("433e9601-1d78-4cca-8b70-baf669adfae5")]
    public partial class RxDatabaseRepository : RepoGenBaseFolder
    {
        static RxDatabaseRepository instance = new RxDatabaseRepository();
        RxDatabaseRepositoryFolders.DemoApplicationAppFolder _demoapplication;
        RxDatabaseRepositoryFolders.DepartmentListAppFolder _departmentlist;

        /// <summary>
        /// Gets the singleton class instance representing the RxDatabaseRepository element repository.
        /// </summary>
        [RepositoryFolder("433e9601-1d78-4cca-8b70-baf669adfae5")]
        public static RxDatabaseRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxDatabaseRepository() 
            : base("RxDatabaseRepository", "/", null, 0, false, "433e9601-1d78-4cca-8b70-baf669adfae5", ".\\RepositoryImages\\RxDatabaseRepository433e9601.rximgres")
        {
            _demoapplication = new RxDatabaseRepositoryFolders.DemoApplicationAppFolder(this);
            _departmentlist = new RxDatabaseRepositoryFolders.DepartmentListAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("433e9601-1d78-4cca-8b70-baf669adfae5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The DemoApplication folder.
        /// </summary>
        [RepositoryFolder("d074c66c-e8e3-4f93-a541-de29a8eb9569")]
        public virtual RxDatabaseRepositoryFolders.DemoApplicationAppFolder DemoApplication
        {
            get { return _demoapplication; }
        }

        /// <summary>
        /// The DepartmentList folder.
        /// </summary>
        [RepositoryFolder("ea3ee1bb-76a8-48fa-93a0-0a935a5739df")]
        public virtual RxDatabaseRepositoryFolders.DepartmentListAppFolder DepartmentList
        {
            get { return _departmentlist; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class RxDatabaseRepositoryFolders
    {
        /// <summary>
        /// The DemoApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("d074c66c-e8e3-4f93-a541-de29a8eb9569")]
        public partial class DemoApplicationAppFolder : RepoGenBaseFolder
        {
            RxDatabaseRepositoryFolders.DatabaseTabFolder _databasetab;
            RepoItemInfo _databaseInfo;
            RepoItemInfo _btnexitInfo;

            /// <summary>
            /// Creates a new DemoApplication  folder.
            /// </summary>
            public DemoApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DemoApplication", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "d074c66c-e8e3-4f93-a541-de29a8eb9569", "")
            {
                _databasetab = new RxDatabaseRepositoryFolders.DatabaseTabFolder(this);
                _databaseInfo = new RepoItemInfo(this, "Database", "?/?/tabpage[@accessiblename='Test database']", 30000, null, "44a1f073-f9bd-4c27-8a7b-2d78baeb8274");
                _btnexitInfo = new RepoItemInfo(this, "BtnExit", "button[@controlname='RxButtonExit']", 30000, null, "2598a21b-f421-414d-9b6d-0cdcb44cbd8c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d074c66c-e8e3-4f93-a541-de29a8eb9569")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d074c66c-e8e3-4f93-a541-de29a8eb9569")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Database item.
            /// </summary>
            [RepositoryItem("44a1f073-f9bd-4c27-8a7b-2d78baeb8274")]
            public virtual Ranorex.TabPage Database
            {
                get
                {
                    return _databaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Database item info.
            /// </summary>
            [RepositoryItemInfo("44a1f073-f9bd-4c27-8a7b-2d78baeb8274")]
            public virtual RepoItemInfo DatabaseInfo
            {
                get
                {
                    return _databaseInfo;
                }
            }

            /// <summary>
            /// The BtnExit item.
            /// </summary>
            [RepositoryItem("2598a21b-f421-414d-9b6d-0cdcb44cbd8c")]
            public virtual Ranorex.Button BtnExit
            {
                get
                {
                    return _btnexitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnExit item info.
            /// </summary>
            [RepositoryItemInfo("2598a21b-f421-414d-9b6d-0cdcb44cbd8c")]
            public virtual RepoItemInfo BtnExitInfo
            {
                get
                {
                    return _btnexitInfo;
                }
            }

            /// <summary>
            /// The DatabaseTab folder.
            /// </summary>
            [RepositoryFolder("d1b35100-06b2-4568-84e6-678337240c68")]
            public virtual RxDatabaseRepositoryFolders.DatabaseTabFolder DatabaseTab
            {
                get { return _databasetab; }
            }
        }

        /// <summary>
        /// The DatabaseTabFolder folder.
        /// </summary>
        [RepositoryFolder("d1b35100-06b2-4568-84e6-678337240c68")]
        public partial class DatabaseTabFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _ageInfo;
            RepoItemInfo _selectmaleInfo;
            RepoItemInfo _btndepartmentlistInfo;
            RepoItemInfo _btnaddentryInfo;
            RepoItemInfo _counterentriesInfo;

            /// <summary>
            /// Creates a new DatabaseTab  folder.
            /// </summary>
            public DatabaseTabFolder(RepoGenBaseFolder parentFolder) :
                    base("DatabaseTab", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "d1b35100-06b2-4568-84e6-678337240c68", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First name']", 30000, null, "81f54b8e-b469-4ddf-8645-58956dc3b68e");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last name']", 30000, null, "c3b3978e-28c5-4d20-bf22-9a3b5d142105");
                _ageInfo = new RepoItemInfo(this, "Age", "?/?/text[@controlname='upDownEdit']", 30000, null, "25d04ce8-a039-4f0d-b3fc-9b4c5d26dbbf");
                _selectmaleInfo = new RepoItemInfo(this, "SelectMale", "?/?/radiobutton[@controlname='rdbMale']", 30000, null, "d0f03f67-3675-44cd-8006-ffd22a31d11f");
                _btndepartmentlistInfo = new RepoItemInfo(this, "BtnDepartmentList", "?/?/button[@accessiblename='Open']", 30000, null, "01449310-d7ae-47b7-a46b-526a69c3ffb6");
                _btnaddentryInfo = new RepoItemInfo(this, "BtnAddEntry", "button[@controlname='btnAddPerson']", 30000, null, "a4abb092-12b3-4466-8d6d-7e61b59a63f7");
                _counterentriesInfo = new RepoItemInfo(this, "CounterEntries", "text[@controlname='lblNumberOfPersonsNumber']", 30000, null, "0943dd17-acbb-4738-bf91-f7e22de8636c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d1b35100-06b2-4568-84e6-678337240c68")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d1b35100-06b2-4568-84e6-678337240c68")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("81f54b8e-b469-4ddf-8645-58956dc3b68e")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("81f54b8e-b469-4ddf-8645-58956dc3b68e")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("c3b3978e-28c5-4d20-bf22-9a3b5d142105")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("c3b3978e-28c5-4d20-bf22-9a3b5d142105")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Age item.
            /// </summary>
            [RepositoryItem("25d04ce8-a039-4f0d-b3fc-9b4c5d26dbbf")]
            public virtual Ranorex.Text Age
            {
                get
                {
                    return _ageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Age item info.
            /// </summary>
            [RepositoryItemInfo("25d04ce8-a039-4f0d-b3fc-9b4c5d26dbbf")]
            public virtual RepoItemInfo AgeInfo
            {
                get
                {
                    return _ageInfo;
                }
            }

            /// <summary>
            /// The SelectMale item.
            /// </summary>
            [RepositoryItem("d0f03f67-3675-44cd-8006-ffd22a31d11f")]
            public virtual Ranorex.RadioButton SelectMale
            {
                get
                {
                    return _selectmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The SelectMale item info.
            /// </summary>
            [RepositoryItemInfo("d0f03f67-3675-44cd-8006-ffd22a31d11f")]
            public virtual RepoItemInfo SelectMaleInfo
            {
                get
                {
                    return _selectmaleInfo;
                }
            }

            /// <summary>
            /// The BtnDepartmentList item.
            /// </summary>
            [RepositoryItem("01449310-d7ae-47b7-a46b-526a69c3ffb6")]
            public virtual Ranorex.Button BtnDepartmentList
            {
                get
                {
                    return _btndepartmentlistInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnDepartmentList item info.
            /// </summary>
            [RepositoryItemInfo("01449310-d7ae-47b7-a46b-526a69c3ffb6")]
            public virtual RepoItemInfo BtnDepartmentListInfo
            {
                get
                {
                    return _btndepartmentlistInfo;
                }
            }

            /// <summary>
            /// The BtnAddEntry item.
            /// </summary>
            [RepositoryItem("a4abb092-12b3-4466-8d6d-7e61b59a63f7")]
            public virtual Ranorex.Button BtnAddEntry
            {
                get
                {
                    return _btnaddentryInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddEntry item info.
            /// </summary>
            [RepositoryItemInfo("a4abb092-12b3-4466-8d6d-7e61b59a63f7")]
            public virtual RepoItemInfo BtnAddEntryInfo
            {
                get
                {
                    return _btnaddentryInfo;
                }
            }

            /// <summary>
            /// The CounterEntries item.
            /// </summary>
            [RepositoryItem("0943dd17-acbb-4738-bf91-f7e22de8636c")]
            public virtual Ranorex.Text CounterEntries
            {
                get
                {
                    return _counterentriesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CounterEntries item info.
            /// </summary>
            [RepositoryItemInfo("0943dd17-acbb-4738-bf91-f7e22de8636c")]
            public virtual RepoItemInfo CounterEntriesInfo
            {
                get
                {
                    return _counterentriesInfo;
                }
            }
        }

        /// <summary>
        /// The DepartmentListAppFolder folder.
        /// </summary>
        [RepositoryFolder("ea3ee1bb-76a8-48fa-93a0-0a935a5739df")]
        public partial class DepartmentListAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _projectmanagementInfo;

            /// <summary>
            /// Creates a new DepartmentList  folder.
            /// </summary>
            public DepartmentListAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DepartmentList", "/list[@controlid='1000']", parentFolder, 30000, null, true, "ea3ee1bb-76a8-48fa-93a0-0a935a5739df", "")
            {
                _projectmanagementInfo = new RepoItemInfo(this, "ProjectManagement", "listitem[@text='Project Management']", 30000, null, "2ccf86e7-cb7b-4275-80fe-89e49408bdb0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ea3ee1bb-76a8-48fa-93a0-0a935a5739df")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ea3ee1bb-76a8-48fa-93a0-0a935a5739df")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProjectManagement item.
            /// </summary>
            [RepositoryItem("2ccf86e7-cb7b-4275-80fe-89e49408bdb0")]
            public virtual Ranorex.ListItem ProjectManagement
            {
                get
                {
                    return _projectmanagementInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ProjectManagement item info.
            /// </summary>
            [RepositoryItemInfo("2ccf86e7-cb7b-4275-80fe-89e49408bdb0")]
            public virtual RepoItemInfo ProjectManagementInfo
            {
                get
                {
                    return _projectmanagementInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}