///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDatabase
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Uploading recording.
    /// </summary>
    [TestModule("069d7755-38d6-4de5-aad1-318d0469c014", ModuleType.Recording, 1)]
    public partial class Uploading : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RxDatabaseRepository repository.
        /// </summary>
        public static RxDatabaseRepository repo = RxDatabaseRepository.Instance;

        static Uploading instance = new Uploading();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Uploading()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Uploading Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApplication.UIElementTestArea' at 74;13.", repo.DemoApplication.UIElementTestAreaInfo, new RecordItemIndex(0));
            repo.DemoApplication.UIElementTestArea.Click("74;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApplication.RxTabUIElements.RdbRedLight' at 5;8.", repo.DemoApplication.RxTabUIElements.RdbRedLightInfo, new RecordItemIndex(1));
            repo.DemoApplication.RxTabUIElements.RdbRedLight.Click("5;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='Red') on item 'DemoApplication.RxTabUIElements.PnlColourPanel'.", repo.DemoApplication.RxTabUIElements.PnlColourPanelInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.DemoApplication.RxTabUIElements.PnlColourPanelInfo, "BackColor", "Red");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApplication.RxTabUIElements.TreeView' at 12;13.", repo.DemoApplication.RxTabUIElements.TreeViewInfo, new RecordItemIndex(3));
            repo.DemoApplication.RxTabUIElements.TreeView.Click("12;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DemoApplication.RxTabUIElements.RanorizeYourselfIn20Minutes'.", repo.DemoApplication.RxTabUIElements.RanorizeYourselfIn20MinutesInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.DemoApplication.RxTabUIElements.RanorizeYourselfIn20MinutesInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Ranorize yourself in 20 minutes') on item 'DemoApplication.RxTabUIElements.RanorizeYourselfIn20Minutes'.", repo.DemoApplication.RxTabUIElements.RanorizeYourselfIn20MinutesInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.DemoApplication.RxTabUIElements.RanorizeYourselfIn20MinutesInfo, "Text", "Ranorize yourself in 20 minutes");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
