///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDatabase
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Uploading recording.
    /// </summary>
    [TestModule("069d7755-38d6-4de5-aad1-318d0469c014", ModuleType.Recording, 1)]
    public partial class Uploading : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RxDatabaseRepository repository.
        /// </summary>
        public static RxDatabaseRepository repo = RxDatabaseRepository.Instance;

        static Uploading instance = new Uploading();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Uploading()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Uploading Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApplication.UploadTesting' at 46;5.", repo.DemoApplication.UploadTestingInfo, new RecordItemIndex(0));
            repo.DemoApplication.UploadTesting.Click("46;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApplication.RxTabUpload.RBSlow' at 5;5.", repo.DemoApplication.RxTabUpload.RBSlowInfo, new RecordItemIndex(1));
            repo.DemoApplication.RxTabUpload.RBSlow.Click("5;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApplication.RxTabUpload.BtnStartUpload' at 78;15.", repo.DemoApplication.RxTabUpload.BtnStartUploadInfo, new RecordItemIndex(2));
            repo.DemoApplication.RxTabUpload.BtnStartUpload.Click("78;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'Value' to equal the specified value '100'. Associated repository item: 'DemoApplication.RxTabUpload.UploadProgressbar'", repo.DemoApplication.RxTabUpload.UploadProgressbarInfo, new RecordItemIndex(3));
            repo.DemoApplication.RxTabUpload.UploadProgressbarInfo.WaitForAttributeEqual(5000, "Value", "100");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
